### ISSUE TITLE
Volume is not restored after group tts message

### ISSUE THREAD

**Issue by stpenz** [Supergiovane/node-red-contrib-tts-ultimate#27]
Hi, I really like the tts ultimate and use it in our home for announcements.
Unfortunately, when I send a message to a configuration with additional players, the volume for the additional players is not restored. The volume remains at the volume of the announcement.
Additionally, sometimes running tracks are stopped after the announcement and restart from the beginning after selecting "play" in the Sonos app.
Would be great to know what I have done wrong or to get a workaround.
Thanks and best regards
Stefan

**Comment by Supergiovane** [comment]
Hi
These additional players are grouped via Sonos app Grouping procedure, or directly via TTS-Ultimate?
As for the play, if you're playing something while the TTS is spoken, TTS-Ultimate resumes correctly. I have never tried to start playing via Sonos app, but it should also start from where it stopped.

**Comment by stpenz** [comment]
Hi, thanks for the quick reply!
The additional players are grouped directly via TTS-Ultimate.
Before the announcement, there are (usually) no groups. When I send a message to TTS-Ultimate, I can see in the Sonos app that the additional players (which I configured in the TTS-Ultimate node) are grouped. After the TTS is played on the speakers, the group is dissolved, but the volume on the additional speakers is not restored and sometimes the track playback of the current track is not resumed. When turning on the speaker manually afterwards, the track starts playback from the beginning.
Hope that helps.

**Comment by Supergiovane** [comment]
Hi
Tomorrow i’ll take a look but this particular issue was already fixed times ago. After leaving the group, the volume is restored for each player. Maybe there is an hiccups…. I’ll take a shot tomorrow

**Comment by Supergiovane** [comment]
Hi stpenz,
i made some changes.
Unfortunately, i have upgraded my sonos stuffs and i've no additional devices compatible with my new sonos anymore, so i cannot test the grouping volume, if it restored correctly.
Please unzip the content of this file into your **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red.
Then try and let me know.

[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/6752444/ttsultimate.js.zip)

**Comment by stpenz** [comment]
Hi, great, the volume is now restored correctly 👍  Thank you so much for taking care!!

Unfortunately, the other issue remains:
- active playback never resumes after an TTS announcement for the additional speakers (but for the main speaker)
- when (re)starting the additional speaker manually after an TTS announcement, tunein radio stations start playing correctly, but any kind of playlist (e.g. Sonos playlist, local MP3 directory ...) restarts playing from the beginning of the first track of the playlist.
Would be great to have a workaround for that as well.

**Comment by Supergiovane** [comment]
Hi
The auto resuming for additional players will take more time to be developed, because i need to keep track of the current status of each player.
As for the last point, unfortunately i don't have much room to play, because Sonos API's are not well documented. I tried in the past to overcome this issue, without success. You can use the very well built **node-red-contrib-sonos-plus** node, focused more on music handling, to store the current playlist and resume it after TTS-Ultimate has stopped speaking. TTS-Ultimate outputs a message every time it starts and stops speaking.

**Comment by stpenz** [comment]
OK, thanks, I will try to find a workaround

**Comment by Supergiovane** [comment]
See here https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification

Sonospollytts mentioned in the link is the old namenof tts-ultimate.

**Comment by Supergiovane** [comment]
Hi, 
just for your info, i'm in contact with the deveolper of sonos-plus and i'll join part of the development, to fix your issue. But it takes some time...

**Comment by stpenz** [comment]
Hi,
great to hear! If you need more information or if I can help in any way, please let me know!

I have already started to tinker with a workaround with sonos-plus and stumbled about one issue that might be related to the tts-ultimate issue. When I trigger "household.get.groups", the resulting array includes an empty array:
![image](https://user-images.githubusercontent.com/86726714/124505215-47efe080-ddc9-11eb-8966-b40ad4b9acaa.png)

This already leads to a crash at the split node in example 09 from the sonos-plus package:
![image](https://user-images.githubusercontent.com/86726714/124505576-19263a00-ddca-11eb-8afc-ece565f44438.png)

I can imagine that something similar happens when TTS-Ultimate gets the groups for later restoring.

**Comment by Supergiovane** [comment]
Interesting. 
No tts-ultimate has no issues with groups. 
You can also dinamically set the group composition by an input msg. 
Anyway, i’ll raise this array issue to the sonos plus dev.
